spring:
  application:
    name: telegram-service
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      group-id: telegram-service
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'
    topics:
      topic-tg-message: ${TOPIC_TG_MESSAGE}
      topic-exmo-user-info: ${TOPIC_EXMO_USER_INFO}
      topic-exmo-currency-list: ${TOPIC_EXMO_CURRENCY_LIST}
      topic-coinmarketcap-price-conversion: ${TOPIC_COINMARKETCAP_PRICE_CONVERSION}
  telegram:
    botname: ${TG_BOTNAME}
    bottoken: ${TG_BOTTOKEN}