version: '3.5'

services:
  crypto-service:
    image: crypto-service:latest
    container_name: crypto-service
    build:
      context: crypto-service
    ports:
      - "8080:8080"
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: ${MONGO_URI}
      TOPIC_TG_MESSAGE: ${TOPIC_TG_MESSAGE}
      TOPIC_EXMO_USER_INFO: ${TOPIC_EXMO_USER_INFO}
      TOPIC_EXMO_CURRENCY_LIST: ${TOPIC_EXMO_CURRENCY_LIST}
      QUARTZ_CRON_SCHEDULE: ${QUARTZ_CRON_SCHEDULE}
      COINMARKETCAP_URI: ${COINMARKETCAP_URI}
      COINMARKETCAP_API_KEY: ${COINMARKETCAP_API_KEY}
      COINMARKETCAP_CRYPTOCURRENCY: ${COINMARKETCAP_CRYPTOCURRENCY}
      EXMO_BASE_URL: ${EXMO_BASE_URL}
      EXMO_API_VERSION: ${EXMO_API_VERSION}
      EXMO_USER_INFO_URN: ${EXMO_USER_INFO_URN}
      EXMO_CURRENCY_LIST_URN: ${EXMO_CURRENCY_LIST_URN}
      EXMO_API_KEY: ${EXMO_API_KEY}
      EXMO_S_KEY: ${EXMO_S_KEY}
    depends_on:
      - crypto-database
  crypto-database:
    container_name: crypto-database
    image: mongo
    ports:
      - '27018:27017'

  telegram-service:
    image: telegram-service:latest
    container_name: telegram-service
    build:
      context: telegram-service
    ports:
      - "8081:8080"
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      TG_BOTNAME: ${TG_BOTNAME}
      TG_BOTTOKEN: ${TG_BOTTOKEN}
      TOPIC_TG_MESSAGE: ${TOPIC_TG_MESSAGE}
      TOPIC_EXMO_USER_INFO: ${TOPIC_EXMO_USER_INFO}
      TOPIC_EXMO_CURRENCY_LIST: ${TOPIC_EXMO_CURRENCY_LIST}

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-service
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092,INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1