apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-info-config
data:
  crypto-db: crypto
  crypto-db-url: mongodb://crypto-db-service:27017/crypto
  kafka: kafka:9092
  topic-tg-message: TG.MESSAGE
  topic-exmo-user-info: EXMO.USER-INFO
  topic-exmo-currency-list: EXMO.CURRENCY-LIST
  topic-coinmarketcap-price-conversion: COINMARKETCAP.PRICE-CONVERSION
  quartz-cron-schedule: 0/30 * * * * ?

  coinmarketcap-base-url: https://pro-api.coinmarketcap.com
  coinmarketcap-api-version: /v2
  cryptocurrency-latest-urn: /cryptocurrency/quotes/latest
  coinmarketcap-price-conversion-urn: /tools/price-conversion
  coinmarketcap-cryptocurrency: BTC,ETH,BNB,XRP,DOGE,TRX,TON,SHIB,PEPE,FLOKI,TURBO
  exmo-base-url: https://api.exmo.com
  exmo-api-version: /v1.1
  exmo-user-info-urn: /user_info
  exmo-currency-list-urn: /currency/list/extended
  tg-botname: CryptoExchangeInfoBot