spring:
  application:
    name: crypto-service
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      group-id: crypto-service
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: eu.senla.shared.dto.TgDataDto
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    topics:
      topic-tg-message: ${TOPIC_TG_MESSAGE}
      topic-exmo-user-info: ${TOPIC_EXMO_USER_INFO}
      topic-exmo-currency-list: ${TOPIC_EXMO_CURRENCY_LIST}
      topic-coinmarketcap-price-conversion: ${TOPIC_COINMARKETCAP_PRICE_CONVERSION}

quartz:
  cron-schedule: ${QUARTZ_CRON_SCHEDULE}

coinmarketcap:
  base-url: ${COINMARKETCAP_BASE_URL}
  api-version: ${COINMARKETCAP_API_VERSION}
  cryptocurrency-latest-urn: ${COINMARKETCAP_CRYPTOCURRENCY_LATEST_URN}
  price-conversion-urn: ${COINMARKETCAP_PRICE_CONVERSION_URN}
  api-key: ${COINMARKETCAP_API_KEY}
  cryptocurrency: ${COINMARKETCAP_CRYPTOCURRENCY}

exmo:
  base-url: ${EXMO_BASE_URL}
  api-version: ${EXMO_API_VERSION}
  user-info-urn: ${EXMO_USER_INFO_URN}
  currency-list-urn: ${EXMO_CURRENCY_LIST_URN}
  api-key: ${EXMO_API_KEY}
  s-key: ${EXMO_S_KEY}
