spring:
  application:
    name: crypto-service
  data:
    mongodb:
      database: crypto
      uri: mongodb://localhost:27017/crypto
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      group-id: crypto-service
      bootstrap-servers: localhost:29092
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: eu.senla.cryptoservice.dto.TgDataDto
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    topics:
      topic-tg-message: TG.MESSAGE
      topic-exmo-user-info: EXMO.USER-INFO

coinmarketcap:
  uri: https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?symbol=BTC
  api-key:

exmo:
  uri: https://api.exmo.com/v1.1/user_info
  api-key:
  s-key:


