apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  namespace: crypto-info
  labels:
    app: telegram-service
spec:
  selector:
    app: telegram-service-container
  ports:
    - name: telegram-service
      port: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-service-deployment
  namespace: crypto-info
  labels:
    app: telegram-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-service-container
  template:
    metadata:
      labels:
        app: telegram-service-container
    spec:
      containers:
        - name: telegram-service-container
          image: starmdd/telegram-service
          imagePullPolicy: Always
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: kafka
            - name: TOPIC_TG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: topic-tg-message
            - name: TOPIC_EXMO_USER_INFO
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: topic-exmo-user-info
            - name: TOPIC_EXMO_CURRENCY_LIST
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: topic-exmo-currency-list
            - name: TOPIC_COINMARKETCAP_PRICE_CONVERSION
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: topic-coinmarketcap-price-conversion
            - name: TG_BOTNAME
              valueFrom:
                configMapKeyRef:
                  name: crypto-info-config
                  key: tg-botname
            - name: TG_BOTTOKEN
              valueFrom:
                secretKeyRef:
                  name: crypto-info-secret
                  key: tg-bottoken
